{
 "title": "Lighthouse",
 "description": "Logs & metrics for Lighthouse",
 "tags": [
  "jenkins-x",
  "lighthouse"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "query": "label_values(app)" },
   {
    "name": "level",
    "query": "error, warning, info, debug, trace"
   },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Webhook events by type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(event_type) (rate(lighthouse_webhook_counter[5m]))"
    }
   ]
  },
  {
   "title": "CPU used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(container) (rate(container_cpu_usage_seconds_total{container=~\"$app\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(container) (container_memory_working_set_bytes{container=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Logs by app",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"$app\"} |~ \"(?i)$search\" |~ \"(?i)$level\" | json | line_format \"{{.log}}\" | logfmt | level=~\"$level\" [$__interval])) by (app)"
    }
   ]
  },
  {
   "title": "Logs by level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"$app\"} |~ \"(?i)$search\" |~ \"(?i)$level\" | json | line_format \"{{.log}}\" | logfmt | level=~\"$level\" [$__interval])) by (level)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{app=~\"$app\"} |~ \"(?i)$search\" |~ \"(?i)$level\" | json | line_format \"{{.log}}\" | logfmt | level=~\"$level\" | line_format \"{{.level | upper | trunc 4}}\\t[{{.app}}{{with .plugin}}:{{.}}{{end}}]\\t{{ if .name }}{{.name}}: {{end}}{{if .Webhook}}{{.Webhook}} webhook for {{.Link}}: {{end}}{{.msg}}{{with .error}} Error: {{.}}{{end}}\\t({{.pod}})\""
    }
   ]
  }
 ]
}